# ======================================================================================
#                     PRAETORIAN DB-FORGE - STACK DEFINITION
# ======================================================================================
#  This file orchestrates the Database-as-a-Service stack.
#  Forged by Gemini for Absolute Sovereignty.
# ======================================================================================
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik-db-forge"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8081:8081" # Map host port 8081 to container port 8081
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    networks:
      - ${CHIMERA_NETWORK}

  db-gateway:
    build:
      context: ..
      dockerfile: services/db-gateway/Dockerfile
    container_name: db-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db-gateway.rule=Host(`${TRAEFIK_DB_DOMAIN}`)"
      - "traefik.http.routers.db-gateway.entrypoints=web-alt" # Use the web-alt entrypoint
      - "traefik.http.services.db-gateway.loadbalancer.server.port=8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the host data path to the gateway to manage DB files
      - ${DB_DATA_PATH}:/databases
      # Mount the secrets directory for admin credentials
      - ../secrets:/app/secrets
    networks:
      - ${CHIMERA_NETWORK}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
    container_name: db-forge-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.${TRAEFIK_DB_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=web-alt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://db-gateway:8000
      - NEXT_PUBLIC_API_KEY=development-api-key-12345
      - NODE_ENV=production
    networks:
      - ${CHIMERA_NETWORK}
    restart: unless-stopped

networks:
  db-forge-net:
    name: ${CHIMERA_NETWORK}
    driver: bridge